spring:
  application:
    name: Exposed demo
  datasource:
    driverClassName: org.h2.Driver
    platform: postgres
    url: jdbc:h2:mem:myTest
    //url: jdbc:h2:~/h2/myTest
    username: sa
    password:

logging:
  level:
    Exposed: DEBUG
    org.ktorm: DEBUG
    root: error
